import {
  createCliente,
  updateCliente,
  deleteCliente,
  createCoach,
  updateCoach,
  deleteCoach,
  createConcepto,
  updateConcepto,
  deleteConcepto,
  createCurso,
  updateCurso,
  deleteCurso,
  createModalidad,
  updateModalidad,
  deleteModalidad,
  getClientes,
  getCoaches,
  getConceptos,
  getCursos,
  getModalidades,
  getProveedores,
  createProveedor,
  updateProveedor,
  deleteProveedor,
  getUnidadesNegocio,
  createUnidadNegocio,
  updateUnidadNegocio,
  deleteUnidadNegocio,
} from './api'

export const CATALOG_DEFINITIONS = {
  clientes: {
    title: 'Empresas',
    subtitle: 'Catálogo de clientes y empresas',
    idField: 'ClienteId',
    fetch: getClientes,
    create: createCliente,
    update: updateCliente,
    delete: deleteCliente,
    columns: [
      { header: 'ID', accessor: 'ClienteId' },
      { header: 'Nombre', accessor: 'Nombre' },
    ],
    fields: [{ name: 'Nombre', label: 'Nombre de la empresa', required: true }],
  },
  proveedores: {
    title: 'Proveedores',
    subtitle: 'Catálogo de proveedores para órdenes de compra',
    idField: 'ProveedorId',
    fetch: getProveedores,
    create: createProveedor,
    update: updateProveedor,
    delete: deleteProveedor,
    columns: [
      { header: 'ID', accessor: 'ProveedorId' },
      { header: 'Proveedor', accessor: 'Nombre' },
      { header: 'RFC', accessor: 'RFC' },
      { header: 'Correo', accessor: 'Correo' },
      { header: 'Teléfono', accessor: 'Telefono' },
    ],
    fields: [
      { name: 'Nombre', label: 'Nombre del proveedor', required: true },
      { name: 'RFC', label: 'RFC', required: false },
      { name: 'Correo', label: 'Correo electrónico', type: 'text' },
      { name: 'Telefono', label: 'Teléfono', type: 'text' },
    ],
  },
  unidadesNegocio: {
    title: 'Unidad de Negocio',
    subtitle: 'Catálogo de unidades de negocio para órdenes de compra',
    idField: 'UnidadNegocioId',
    fetch: getUnidadesNegocio,
    create: createUnidadNegocio,
    update: updateUnidadNegocio,
    delete: deleteUnidadNegocio,
    columns: [
      { header: 'ID', accessor: 'UnidadNegocioId' },
      { header: 'Unidad de negocio', accessor: 'Nombre' },
      { header: 'Responsable', accessor: 'Responsable' },
    ],
    fields: [
      { name: 'Nombre', label: 'Nombre de la unidad', required: true },
      { name: 'Responsable', label: 'Responsable', type: 'text' },
    ],
  },
  cursos: {
    title: 'Cursos',
    subtitle: 'Catálogo de programas y cursos',
    idField: 'CursoId',
    fetch: getCursos,
    create: createCurso,
    update: updateCurso,
    delete: deleteCurso,
    columns: [
      { header: 'ID', accessor: 'CursoId' },
      { header: 'Nombre', accessor: 'Nombre' },
      { header: 'Tipo', accessor: 'TipoCurso' },
      { header: 'Horas', accessor: 'Horas' },
      { header: 'Costo', accessor: 'Costo' },
      { header: 'Duración (días)', accessor: 'DuracionDefaultDias' },
    ],
    fields: [
      { name: 'Nombre', label: 'Nombre del curso', required: true },
      { name: 'TipoCurso', label: 'Tipo de curso', type: 'select', options: [
        { value: '', label: '-- Seleccionar --' },
        { value: 'Mandatorio', label: 'Mandatorio' },
        { value: 'Extraordinario', label: 'Extraordinario' },
      ]},
      { name: 'Horas', label: 'Horas', type: 'number' },
      { name: 'Costo', label: 'Costo ($)', type: 'number' },
      { name: 'DuracionDefaultDias', label: 'Duración por defecto (días)', type: 'number' },
    ],
  },
  coaches: {
    title: 'Coaches',
    subtitle: 'Catálogo de coaches e instructores',
    idField: 'CoachId',
    fetch: getCoaches,
    create: createCoach,
    update: updateCoach,
    delete: deleteCoach,
    columns: [
      { header: 'ID', accessor: 'CoachId' },
      { header: 'Nombre', accessor: 'Nombre' },
      {
        header: 'Costo',
        accessor: 'Costo',
        render: (value) => (value != null ? `$ ${Number(value).toFixed(2)}` : '-'),
      },
    ],
    fields: [
      { name: 'Nombre', label: 'Nombre del coach', required: true },
      { name: 'Costo', label: 'Costo ($)', type: 'number', step: '0.01' },
    ],
  },
  modalidades: {
    title: 'Modalidades',
    subtitle: 'Catálogo de modalidades disponibles',
    idField: 'ModalidadId',
    fetch: getModalidades,
    create: createModalidad,
    update: updateModalidad,
    delete: deleteModalidad,
    columns: [
      { header: 'ID', accessor: 'ModalidadId' },
      { header: 'Nombre', accessor: 'Nombre' },
    ],
    fields: [{ name: 'Nombre', label: 'Nombre de la modalidad', required: true }],
  },
  conceptos: {
    title: 'Conceptos de Costo',
    subtitle: 'Catálogo de conceptos de costo',
    idField: 'ConceptoCostoId',
    fetch: getConceptos,
    create: createConcepto,
    update: updateConcepto,
    delete: deleteConcepto,
    columns: [
      { header: 'ID', accessor: 'ConceptoCostoId' },
      { header: 'Concepto', accessor: 'Nombre' },
      { header: 'Tipo de costo', accessor: 'TipoCosto' },
      { header: 'Tipo de cálculo', accessor: 'TipoCalculo' },
      { header: 'Fórmula', accessor: 'Formula' },
      {
        header: 'Costo unitario',
        accessor: 'CostoUnitario',
        render: (value) => (value != null ? `$ ${Number(value).toFixed(2)}` : '-'),
      },
    ],
    fields: [
      {
        name: 'TipoCosto',
        label: 'Tipo de costo',
        type: 'select',
        options: [
          { value: 'Directos', label: 'Directos' },
          { value: 'Indirectos', label: 'Indirectos' },
        ],
        placeholder: 'Selecciona tipo de costo',
        required: true,
      },
      { name: 'Nombre', label: 'Concepto', required: true },
      {
        name: 'TipoCalculo',
        label: 'Tipo de cálculo',
        type: 'select',
        options: [
          { value: 'Por sesión', label: 'Por sesión' },
          { value: 'Por participante', label: 'Por participante' },
          { value: 'Por evento', label: 'Por evento' },
          { value: 'Por hora', label: 'Por hora' },
          { value: 'Por día', label: 'Por día' },
        ],
        placeholder: 'Selecciona cómo se costeará',
        required: true,
      },
      {
        name: 'Formula',
        label: 'Fórmula',
        placeholder: 'Ej: Sesiones x Días, Participantes, Eventos, Horas',
        required: true,
      },
      { name: 'CostoUnitario', label: 'Costo unitario', type: 'number', step: '0.01', required: true },
    ],
  },
  proveedores: {
    title: 'Proveedores',
    subtitle: 'Catálogo de proveedores para las órdenes de compra',
    idField: 'ProveedorId',
    fetch: getProveedores,
    create: createProveedor,
    update: updateProveedor,
    delete: deleteProveedor,
    columns: [
      { header: 'ID', accessor: 'ProveedorId' },
      { header: 'Nombre', accessor: 'Nombre' },
      { header: 'Contacto', accessor: 'Contacto' },
      { header: 'Teléfono', accessor: 'Telefono' },
    ],
    fields: [
      { name: 'Nombre', label: 'Nombre del proveedor', required: true },
      { name: 'Contacto', label: 'Persona de contacto' },
      { name: 'Telefono', label: 'Teléfono', type: 'text' },
      { name: 'Email', label: 'Correo electrónico', type: 'text' },
    ],
  },
  unidadesNegocio: {
    title: 'Unidades de negocio',
    subtitle: 'Catálogo de unidades de negocio para órdenes de compra',
    idField: 'UnidadNegocioId',
    fetch: getUnidadesNegocio,
    create: createUnidadNegocio,
    update: updateUnidadNegocio,
    delete: deleteUnidadNegocio,
    columns: [
      { header: 'ID', accessor: 'UnidadNegocioId' },
      { header: 'Nombre', accessor: 'Nombre' },
      { header: 'Responsable', accessor: 'Responsable' },
    ],
    fields: [
      { name: 'Nombre', label: 'Nombre de la unidad de negocio', required: true },
      { name: 'Responsable', label: 'Responsable' },
      { name: 'Area', label: 'Área' },
    ],
  },
}

export function emptyFormForCatalog(catalogKey) {
  const fields = CATALOG_DEFINITIONS[catalogKey]?.fields || []
  return fields.reduce((acc, field) => {
    acc[field.name] = ''
    return acc
  }, {})
}
